import * as React from 'react';
import ResponsiveAppBar from './components/Navbar/Navbar';
import './components/Scrollbar/Scrollbar.css'

function App() {
  return (
    <div>
      <ResponsiveAppBar/>
      <div>eiei</div>
      <div>eiei</div>
      <div>eiei</div>
      <div>eiei</div>
      <div>eiei</div>
      <div>eiei</div>
      <div>eiei</div>
      <div>eiei</div>
      <div>eiei</div>
      <div>eiei</div>
      <div>eiei</div>
      <div>eiei</div>
      <div>eiei</div>
      <div>eiei</div>
      <div>eiei</div>
      <div>eiei</div>
      <div>eiei</div>
      <div>eiei</div>
      <div>eiei</div>
      <div>eiei</div>
      <div>eiei</div>
      <div>eiei</div>
      <div>eiei</div>
      <div>eiei</div>
      <div>eiei</div>
      <div>eiei</div>
      <div>eiei</div>
      <div>eiei</div>
      <div>eiei</div>
      <div>eiei</div>
      <div>eiei</div>
      <div>eiei</div>
      <div>eiei</div>
      <div>eiei</div>
      <div>eiei</div>
      <div>eiei</div>
      <div>eiei</div>
      <div>eiei</div>
      <div>eiei</div>
      <div>eiei</div>
      <div>eiei</div>
      <div>eiei</div>
      <div>eiei</div>
      <div>eiei</div>
      <div>eiei</div>
      <div>eiei</div>
      <div>eiei</div>
      <div>eiei</div>
      <div>eiei</div>
      <div>eiei</div>
      <div>eiei</div>
      <div>eiei</div>
      <div>eiei</div>
      <div>eiei</div>
      <div>eiei</div>
      <div>eiei</div>
      <div>eiei</div>
      <div>eiei</div>
      <div>eiei</div>
      <div>eiei</div>
      <div>eiei</div>
      <div>eiei</div>
      <div>eiei</div>
      <div>eiei</div>
      <div>eiei</div>
      <div>eiei</div>
      <div>eiei</div>
      <div>eiei</div>
      <div>eiei</div>
      <div>eiei</div>
      <div>eiei</div>
      <div>eiei</div>
      <div>eiei</div>
      <div>eiei</div>
      <div>eiei</div>
      <div>eiei</div>
      <div>eiei</div>
      <div>eiei</div>
      <div>eiei</div>
      <div>eiei</div>
      <div>eiei</div>
      <div>eiei</div>
      <div>eiei</div>
      <div>eiei</div>
      <div>eiei</div>
      <div>eiei</div>
      <div>eiei</div>
      <div>eiei</div>
      <div>eiei</div>
      <div>eiei</div>
      <div>eiei</div>
      <div>eiei</div>
      <div>eiei</div>
      <div>eiei</div>
      <div>eiei</div>
      <div>eiei</div>
      <div>eiei</div>
      <div>eiei</div>
      <div>eiei</div>
      <div>eiei</div>
      <div>eiei</div>
      <div>eiei</div>
      <div>eiei</div>
      <div>eiei</div>
      <div>eiei</div>
      <div>eiei</div>
      <div>eiei</div>
      <div>eiei</div>
      <div>eiei</div>
      <div>eiei</div>
      <div>eiei</div>
      <div>eiei</div>
      <div>eiei</div>
      <div>eiei</div>
      <div>eiei</div>
      <div>eiei</div>
      <div>eiei</div>
    </div>
  );
}

export default App;
